displayName: Header2Post
type: middleware
iconPath: .assets/logo.png

import: github.com/94peter/header2post

summary: 'check notify header exist and use http post to url'

testData:
  notifyheader: X-Notify
  notifyurl: http://localhost:8000